# Update interval in seconds
update-interval: 30

# Debug settings
debug:
  enabled: false
  log-updates: false
  log-texture-cache: false

# Texture Cache Settings
texture-cache:
  enabled: true
  expiry-days: 7 # How many days to keep cached textures
  max-size: 1000 # Maximum number of player textures to cache

# GUI Settings
gui:
  title: "Leaderboards - {type}"
  size: 54 # 6 rows
  navigation:
    next-page:
      slot: 50
      item: ARROW
      name: "§aNext Page"
    previous-page:
      slot: 48
      item: ARROW
      name: "§aPrevious Page"

# Leaderboard Types
leaderboards:
  mobkills:
    title: "Top Mob Kills"
    placeholder: "%statistic_mob_kills%"
    format: "{position}. {player}: {value} kills"
  blocks:
    title: "Top Blocks Mined"
    placeholder: "%statistic_mine_block%"
    format: "{position}. {player}: {value} blocks"



